=== javarias/scheduling/Common/config/executive.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="ExecutiveData">
		<xs:key name="ExecutivePercentageKey">
			<xs:selector xpath="./ExecutivePercentage" />
			<xs:field xpath="id" />
		</xs:key>
		<xs:keyref name="ExecutivePercentageRef" refer="ExecutivePercentageKey">
			<xs:selector xpath="./Executive" />
			<xs:field xpath="idref" />
		</xs:keyref>
	</xs:element>

	<xs:complexType name="ExecutiveData">
		<xs:sequence>
			<xs:element name="ObservingSeason" type="ObservingSeason" />
			<xs:element name="Executive" type="Executive" />
			<xs:element name="ExecutiveTimeSpent" type="ExecutiveTimeSpent" />
			<xs:element name="ExecutivePercentage" type="ExecutivePercentage" />
			<xs:element name="PI" type="PI" />
			<xs:element name="PIMembership" type="PIMembership" />
			<xs:element name="SchedBlockExecutivePercentage" type="SchedBlockExecutivePercentage" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ExecutiveTimeSpent">
		<xs:sequence>
			<xs:element name="season" type="ObservingSeason"
				minOccurs="1" maxOccurs="1" />
			<xs:element name="timeSpent" type="xs:float" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="ObservingSeason" type="ObservingSeason"
				minOccurs="1" maxOccurs="1" />
			<xs:element name="Executive" type="Executive" minOccurs="1"
				maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="PI">
		<xs:sequence>
			<xs:element name="name" type="xs:string" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="PIMembership" type="PIMembership"
				minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ObservingSeason">
		<xs:sequence>
			<xs:element name="endDate" type="xs:date" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="name" type="xs:string" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="startDate" type="xs:date" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="ExecutivePercentage" type="ExecutivePercentage"
				minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Executive">
		<xs:sequence>
			<xs:element name="defaultPercentage" type="xs:float"
				minOccurs="1" maxOccurs="1" />
			<xs:element name="name" type="xs:string" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="executivePercentage" type="xs:NCName"
				minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="SchedBlockExecutivePercentage" type="SchedBlockExecutivePercentage"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ExecutivePercentage">
		<xs:sequence>
			<xs:element name="id" type="xs:long" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="percentage" type="xs:float" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="totalObsTimeForSeason" type="xs:float"
				minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="PIMembership">
		<xs:sequence>
			<xs:element name="membershipPercentage" type="xs:float"
				minOccurs="1" maxOccurs="1" />
			<xs:element name="Executive" type="Executive" minOccurs="1"
				maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="SchedBlockExecutivePercentage">
		<xs:sequence>
			<xs:element name="executionTime" type="xs:long" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="percentage" type="xs:float" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="sbid" type="xs:string" minOccurs="1"
				maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== javarias/scheduling/Common/test/projects/SimpleDSATest01/executive/executive.xml
<?xml version="1.0" encoding="UTF-8"?>
<ExecutiveData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../config/executive.xsd">
<!--
This use case uses the fictional countries of Salsasia and Conservia.
Both of them has one astromer.
The time are equally divided. It only serves the porpuses to test the Executive Ranker of the DSA
-->
	<Executive>
		<defaultPercentage>50.0</defaultPercentage>
		<name>Salsasia</name>
		<ExecutivePercentageRef idRef="SalsaciaPercentage" />
	</Executive>
	<Executive>
		<defaultPercentage>50.0</defaultPercentage>
		<name>Conservia</name>
		<ExecutivePercentageRef idRef="ConverviaPercentage" />
	</Executive>
	<ObservingSeason id="OS">
		<endDate>2011-01-01</endDate>
		<name>name</name>
		<startDate>2011-01-02</startDate>
		<ExecutivePercentageRef idRef="SalsaciaPercentage" />
		<ExecutivePercentageRef idRef="ConverviaPercentage" />		
	</ObservingSeason>
	<ExecutivePercentage id="SalsaciaPercentage">
		<percentage>50.0</percentage>
		<totalObsTimeForSeason>0.0</totalObsTimeForSeason>
	</ExecutivePercentage>
	<ExecutivePercentage id="ConverviaPercentage">
		<percentage>50.0</percentage>
		<totalObsTimeForSeason>0.0</totalObsTimeForSeason>
	</ExecutivePercentage>
	<PI>
		<name>Astronomer from Salsasia</name>
		<PIMembership>
			<membershipPercentage>100.0</membershipPercentage>
			<ExecutiveRef nameRef="Salsasia" />
		</PIMembership>
	</PI>
	<PI>
		<name>Astronomer from Conservia</name>
		<PIMembership>
			<membershipPercentage>100.0</membershipPercentage>
			<ExecutiveRef nameRef="Conservia" />
		</PIMembership>
	</PI>

</ExecutiveData>
