=== javarias/scheduling/PlanningModeSim/Engine/config/Weather.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!-- Example Schema for the Weather Data collected from the WeatherStations -->
    <xs:element name="WeatherParameters">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="WeatherStation" type="WeatherStationT" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="WeatherStationT">
        <xs:sequence>
            <xs:element name="Location">
                <!-- The distance, in meters, from the centre of the earth. These
                     are in the ITRF reference frame. -->
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="X" type="xs:double"/>
                        <xs:element name="Y" type="xs:double"/>
                        <xs:element name="Z" type="xs:double"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="WeatherData" type="WeatherDataT" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="WeatherDataT">
        <xs:sequence>
            <xs:element name="Value" type="WeatherValueT" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="type">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="Pressure"/>
                    <xs:enumeration value="WindSpeed"/>
                    <xs:enumeration value="WindDirection"/>
                    <xs:enumeration value="Temperature"/>
                    <xs:enumeration value="DewPoint"/>
                    <xs:enumeration value="Humidity"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    <xs:complexType name="WeatherValueT">
        <!-- A generic value element, aggregating a timestamp in ACS Time units,
             and a value which unit depends on its type in the following way:
             
             Pressure - Pascals (1 hPa = 100Pa)
             WinSpeed - meters per second
             WinDirection - radians. 0 is north, and pi/2 east
             Temperature - degrees C
             DewPoint - degrees C
             Humidity - relative humidity, between 0 and 1 -->
        <xs:attribute name="timestamp" type="xs:long"/>
        <xs:attribute name="value" type="xs:double"/>
    </xs:complexType>
</xs:schema>

=== javarias/scheduling/PlanningModeSim/Engine/test/Weather.xml
<?xml version="1.0" encoding="UTF-8"?>
<WeatherParameters xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:../config/Weather.xsd">
    <WeatherStation name="WS001">
        <Location>
            <X>2202174.553</X>
            <Y>-5445221.708</Y>
            <Z>-2485330.272</Z>
        </Location>
        <WeatherData type="Pressure">
            <Value timestamp="134758801429267070" value="0.445742202964"/>
            <Value timestamp="134758801439266642" value="0.277101849219"/>
            <Value timestamp="134758801449266820" value="0.0403931702418"/>
            <Value timestamp="134758801459266400" value="0.01681169175"/>
            <Value timestamp="134758801469266490" value="0.0958244326151"/>
            <Value timestamp="134758801479266130" value="0.553036089882"/>
            <Value timestamp="134758801489266250" value="0.516847566803"/>
            <Value timestamp="134758801499265850" value="0.261635257082"/>
            <Value timestamp="134758801509265990" value="0.792385753389"/>
            <Value timestamp="134758801519265590" value="0.769203659488"/>
            <Value timestamp="134758801529265730" value="0.922354444312"/>
            <Value timestamp="134758801539265340" value="0.64643510219"/>
            <Value timestamp="134758801549265470" value="0.459486428931"/>
            <Value timestamp="134758801559265070" value="0.560394227771"/>
            <Value timestamp="134758801569265220" value="0.87960401987"/>
            <Value timestamp="134758801579264810" value="0.206802950449"/>
            <Value timestamp="134758801589262670" value="0.340616843111"/>
            <Value timestamp="134758801599264570" value="0.168826866241"/>
            <Value timestamp="134758801609264690" value="0.665654996889"/>
            <Value timestamp="134758801619264268" value="0.619988516668"/>
            <Value timestamp="134758801629264160" value="0.402903946959"/>
            <Value timestamp="134758801639264210" value="0.167854835982"/>
            <Value timestamp="134758801649263880" value="0.887845332897"/>
            <Value timestamp="134758801659264040" value="0.103131521427"/>
            <Value timestamp="134758801669263640" value="0.553224998458"/>
            <Value timestamp="134758801679263750" value="0.124887236358"/>
            <Value timestamp="134758801689263390" value="0.0203383692512"/>
            <Value timestamp="134758801699263510" value="0.559650956518"/>
            <Value timestamp="134758801709263100" value="0.623847264069"/>
            <Value timestamp="134758801719263238" value="0.461605488448"/>
        </WeatherData>
        <WeatherData type="WindSpeed">
            <Value timestamp="134758801429267070" value="0.445742202964"/>
            <Value timestamp="134758801439266642" value="0.277101849219"/>
            <Value timestamp="134758801449266820" value="0.0403931702418"/>
            <Value timestamp="134758801459266400" value="0.01681169175"/>
            <Value timestamp="134758801469266490" value="0.0958244326151"/>
            <Value timestamp="134758801479266130" value="0.553036089882"/>
            <Value timestamp="134758801489266250" value="0.516847566803"/>
            <Value timestamp="134758801499265850" value="0.261635257082"/>
            <Value timestamp="134758801509265990" value="0.792385753389"/>
            <Value timestamp="134758801519265590" value="0.769203659488"/>
            <Value timestamp="134758801529265730" value="0.922354444312"/>
            <Value timestamp="134758801539265340" value="0.64643510219"/>
            <Value timestamp="134758801549265470" value="0.459486428931"/>
            <Value timestamp="134758801559265070" value="0.560394227771"/>
            <Value timestamp="134758801569265220" value="0.87960401987"/>
            <Value timestamp="134758801579264810" value="0.206802950449"/>
            <Value timestamp="134758801589262670" value="0.340616843111"/>
            <Value timestamp="134758801599264570" value="0.168826866241"/>
            <Value timestamp="134758801609264690" value="0.665654996889"/>
            <Value timestamp="134758801619264268" value="0.619988516668"/>
            <Value timestamp="134758801629264160" value="0.402903946959"/>
            <Value timestamp="134758801639264210" value="0.167854835982"/>
            <Value timestamp="134758801649263880" value="0.887845332897"/>
            <Value timestamp="134758801659264040" value="0.103131521427"/>
            <Value timestamp="134758801669263640" value="0.553224998458"/>
            <Value timestamp="134758801679263750" value="0.124887236358"/>
            <Value timestamp="134758801689263390" value="0.0203383692512"/>
            <Value timestamp="134758801699263510" value="0.559650956518"/>
            <Value timestamp="134758801709263100" value="0.623847264069"/>
            <Value timestamp="134758801719263238" value="0.461605488448"/>
        </WeatherData>
        <WeatherData type="WindDirection">
            <Value timestamp="134758801429267070" value="0.445742202964"/>
            <Value timestamp="134758801439266642" value="0.277101849219"/>
            <Value timestamp="134758801449266820" value="0.0403931702418"/>
            <Value timestamp="134758801459266400" value="0.01681169175"/>
            <Value timestamp="134758801469266490" value="0.0958244326151"/>
            <Value timestamp="134758801479266130" value="0.553036089882"/>
            <Value timestamp="134758801489266250" value="0.516847566803"/>
            <Value timestamp="134758801499265850" value="0.261635257082"/>
            <Value timestamp="134758801509265990" value="0.792385753389"/>
            <Value timestamp="134758801519265590" value="0.769203659488"/>
            <Value timestamp="134758801529265730" value="0.922354444312"/>
            <Value timestamp="134758801539265340" value="0.64643510219"/>
            <Value timestamp="134758801549265470" value="0.459486428931"/>
            <Value timestamp="134758801559265070" value="0.560394227771"/>
            <Value timestamp="134758801569265220" value="0.87960401987"/>
            <Value timestamp="134758801579264810" value="0.206802950449"/>
            <Value timestamp="134758801589262670" value="0.340616843111"/>
            <Value timestamp="134758801599264570" value="0.168826866241"/>
            <Value timestamp="134758801609264690" value="0.665654996889"/>
            <Value timestamp="134758801619264268" value="0.619988516668"/>
            <Value timestamp="134758801629264160" value="0.402903946959"/>
            <Value timestamp="134758801639264210" value="0.167854835982"/>
            <Value timestamp="134758801649263880" value="0.887845332897"/>
            <Value timestamp="134758801659264040" value="0.103131521427"/>
            <Value timestamp="134758801669263640" value="0.553224998458"/>
            <Value timestamp="134758801679263750" value="0.124887236358"/>
            <Value timestamp="134758801689263390" value="0.0203383692512"/>
            <Value timestamp="134758801699263510" value="0.559650956518"/>
            <Value timestamp="134758801709263100" value="0.623847264069"/>
            <Value timestamp="134758801719263238" value="0.461605488448"/>
        </WeatherData>
        <WeatherData type="Temperature">
            <Value timestamp="134758801429267070" value="0.445742202964"/>
            <Value timestamp="134758801439266642" value="0.277101849219"/>
            <Value timestamp="134758801449266820" value="0.0403931702418"/>
            <Value timestamp="134758801459266400" value="0.01681169175"/>
            <Value timestamp="134758801469266490" value="0.0958244326151"/>
            <Value timestamp="134758801479266130" value="0.553036089882"/>
            <Value timestamp="134758801489266250" value="0.516847566803"/>
            <Value timestamp="134758801499265850" value="0.261635257082"/>
            <Value timestamp="134758801509265990" value="0.792385753389"/>
            <Value timestamp="134758801519265590" value="0.769203659488"/>
            <Value timestamp="134758801529265730" value="0.922354444312"/>
            <Value timestamp="134758801539265340" value="0.64643510219"/>
            <Value timestamp="134758801549265470" value="0.459486428931"/>
            <Value timestamp="134758801559265070" value="0.560394227771"/>
            <Value timestamp="134758801569265220" value="0.87960401987"/>
            <Value timestamp="134758801579264810" value="0.206802950449"/>
            <Value timestamp="134758801589262670" value="0.340616843111"/>
            <Value timestamp="134758801599264570" value="0.168826866241"/>
            <Value timestamp="134758801609264690" value="0.665654996889"/>
            <Value timestamp="134758801619264268" value="0.619988516668"/>
            <Value timestamp="134758801629264160" value="0.402903946959"/>
            <Value timestamp="134758801639264210" value="0.167854835982"/>
            <Value timestamp="134758801649263880" value="0.887845332897"/>
            <Value timestamp="134758801659264040" value="0.103131521427"/>
            <Value timestamp="134758801669263640" value="0.553224998458"/>
            <Value timestamp="134758801679263750" value="0.124887236358"/>
            <Value timestamp="134758801689263390" value="0.0203383692512"/>
            <Value timestamp="134758801699263510" value="0.559650956518"/>
            <Value timestamp="134758801709263100" value="0.623847264069"/>
            <Value timestamp="134758801719263238" value="0.461605488448"/>
        </WeatherData>
        <WeatherData type="DewPoint">
            <Value timestamp="134758801429267070" value="0.445742202964"/>
            <Value timestamp="134758801439266642" value="0.277101849219"/>
            <Value timestamp="134758801449266820" value="0.0403931702418"/>
            <Value timestamp="134758801459266400" value="0.01681169175"/>
